name: .NET Core Build/Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      working-directory: ./Src/Newtonsoft.Json.Interface
      run: dotnet restore
    - name: Build
      working-directory: ./Src/Newtonsoft.Json.Interface
      run: dotnet build --configuration Release --no-restore --framework netcoreapp3.1
    - name: Test
      working-directory: ./Src/Newtonsoft.Json.Interface
      run: dotnet test --no-restore --framework netcoreapp3.1
