name: .NET Core Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore /porrey/Newtonsoft.Json.Interface/Src/Newtonsoft.Json.Interface/Newtonsoft.Json.Interface-Solution.sln
    - name: Build
      run: dotnet build /porrey/Newtonsoft.Json.Interface/Src/Newtonsoft.Json.Interface/Newtonsoft.Json.Interface-Solution.sln --configuration Release --framework netcoreapp3.1 --no-restore
    - name: Test
      run: dotnet test /porrey/Newtonsoft.Json.Interface/Src/Newtonsoft.Json.Interface/Newtonsoft.Json.Interface-Solution.sln --framework netcoreapp3.1 --no-restore
