name: .NET Core Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      working-directory: /porrey/Newtonsoft.Json.Interface/Src/Newtonsoft.Json.Interface
      run: dotnet restore
    - name: Build
      working-directory: /porrey/Newtonsoft.Json.Interface/Src/Newtonsoft.Json.Interface
      run: dotnet build --configuration Release --framework netcoreapp3.1
    - name: Test
      working-directory: /porrey/Newtonsoft.Json.Interface/Src/Newtonsoft.Json.Interface
      run: dotnet test --framework netcoreapp3.1
