name: .NET Core Build/Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./src/Newtonsoft.Json.Interface/Newtonsoft.Json.Interface-Solution.sln
    - name: Build
      working-directory: ./src/Newtonsoft.Json.Interface
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./src/Newtonsoft.Json.Interface
      run: dotnet test --no-restore
